all:
  hosts:
    nodo1:
      ansible_host: 192.168.1.1
    nodo2:
      ansible_host: 192.168.1.2
    nodo3:
      ansible_host: 192.168.1.3
    nodo4:
      ansible_host: 192.168.1.4
    nodo5:
      ansible_host: 192.168.1.5
    nodo6:
      ansible_host: 192.168.1.6
    nodo7:
      ansible_host: 192.168.1.7
    nodo8:
      ansible_host: 192.168.1.8
    nodo9:
      ansible_host: 192.168.1.9
    nodo10:
      ansible_host: 192.168.1.10
  vars:
    ansible_user: usuario
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
