- name: Instalar dependencias para Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Agregar la clave GPG de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Agregar el repositorio de Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Instalar Docker
  apt:
    name: docker-ce
    state: present

- name: Agregar el usuario al grupo docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
