- name: Descargar el script de instalación de Miniconda
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/miniconda.sh
    mode: '0755'

- name: Instalar Miniconda
  shell: /tmp/miniconda.sh -b -p /opt/miniconda
  args:
    creates: /opt/miniconda/bin/conda

- name: Agregar Conda al PATH
  lineinfile:
    path: /etc/profile.d/conda.sh
    line: 'export PATH=/opt/miniconda/bin:$PATH'
    create: yes
